### ISSUE TITLE
hellow

### ISSUE THREAD

**Issue by payeer1982** [PXLFuSSeL/ArenonGameWallet#1]
good, how the genesis block is generated for the masternodes, pow / pos coins are made but these, when generating the genesis always gives me fault

**Comment by payeer1982** [comment]
and what algorithm is your currency, thanks

**Comment by PXLFuSSeL** [comment]
Hey if you want to talk about the coin or coin programming, contact me via discord or email.

**Comment by PXLFuSSeL** [comment]
discord PXLFuSSeL#7688
